base_url = "https://gcu.tactical-grace.net"
generate_rss = true
hard_link_static = true

[extra]
grades = [ "hg", "mg", "pg", "rg", "varia" ]
recent_entry_count = 3
imgurl = "https://gcu.tactical-grace.net/photos"
