base_url = 'https://gcu.tactical-grace.net'
title = 'tactical grace'
description = 'Welcome to tactical grace!'
generate_rss = true
hard_link_static = true

[extra]
grades = [ 'hg', 'mg', 'pg', 'rg', 'varia' ]
recent_entry_count = 3
photo_full = '/photos/full/'
photo_thumb = '/photos/thumb/'
