[build]
  publish = "public"
  command = "make build"

[build.environment]
  ZOLA_VERSION = "0.12.2"

[context.deploy-preview]
  command = "make build-netlify-preview"

[context.branch-deploy]
  command = "make build-netlify-preview"

[[redirects]]
  from = "/index.xml"
  to = "rss.xml"
