[build]
  publish = "public"
  command = "zola build && find public -type f -empty -delete && find public -type d -empty -delete"

[build.environment]
  ZOLA_VERSION = "0.8.0"

[context.deploy-preview]
  command = "zola build --base-url $DEPLOY_PRIME_URL && find public -type f -empty -delete && find public -type d -empty -delete"

[context.branch-deploy]
  command = "zola build --base-url $DEPLOY_PRIME_URL && find public -type f -empty -delete && find public -type d -empty -delete"
