[cmd_duration]
show_milliseconds = true

[env_var]
style = "red bold"
variable = "_CONF_UPDATE"

[jobs]
threshold = 0

[time]
disabled = false
format = "[$time]($style) "
time_format = "%b %d %H:%M"

[shlvl]
disabled = false
threshold = 3
symbol = "↕️"

[hostname]
#prefix = "@"
ssh_only = false

[directory]
truncation_length = 8

[status]
disabled = false
symbol = "╳"
