base_url = 'https://gcu.tactical-grace.net'
title = 'tactical grace'
description = 'Welcome to tactical grace!'
generate_feed = true
feed_filename = "rss.xml"
feed_limit = 15
hard_link_static = true

[extra]
# Will dump entire Tera context at the bottom of the page if enabled.
debug = false
# List of all grades. Anything else than this might be rendered but won't get
# enumerated by the summary pages.
grades = [ 'hg', 'mg', 'pg', 'rg', 'varia' ]
# How many entries should be shown on the main page?
recent_entry_count = 3
# Directory with full photos.
photo_full = '/photos/full/'
# Directory with thumbnails.
photo_thumb = '/photos/thumb/'
